{
  "name": "ui-ux-pro-max",
  "displayName": "UI/UX Pro Max",
  "description": "AI-powered design intelligence with 84 UI styles, 192 color palettes, 74 font pairings, 98 UX guidelines, and 25 chart types across 22 tech stacks.",
  "version": "2.13.0",
  "author": "NextLevelBuilder",
  "license": "MIT",
  "homepage": "https://uupm.cc",
  "repository": "https://github.com/nextlevelbuilder/ui-ux-pro-max-skill",
  "keywords": [
    "ui",
    "ux",
    "design",
    "design-system",
    "color-palette",
    "typography",
    "accessibility",
    "ai-skill"
  ],
  "platforms": [
    "claude",
    "cursor",
    "windsurf",
    "copilot",
    "kiro",
    "roocode",
    "kilocode",
    "codex",
    "qoder",
    "gemini",
    "trae",
    "opencode",
    "continue",
    "codebuddy",
    "droid",
    "warp",
    "augment",
    "antigravity",
    "openclaw"
  ],
  "install": "npx ui-ux-pro-max-cli init --ai {{platform}}"
}
