const https = require('https');

const catalog = [
  // --- K-DRAMAS & TV SERIES ---
  { id: "tv-crash-landing", title: "Crash Landing on You", mediaType: "tv", year: "2019 • 1 Season", rating: 8.8, genres: ["K-Drama", "Romance", "Comedy"], overview: "A paragliding mishap drops a South Korean heiress into North Korea—and into the life of an army officer, who decides to help her hide.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/235/588087.jpg" },
  { id: "tv-queen-of-tears", title: "Queen of Tears", mediaType: "tv", year: "2024 • 1 Season", rating: 8.7, genres: ["K-Drama", "Romance", "Drama"], overview: "The queen of department stores and the prince of supermarkets weather a marital crisis until love miraculously begins to bloom again.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/507/1269260.jpg" },
  { id: "tv-business-proposal", title: "Business Proposal", mediaType: "tv", year: "2022 • 1 Season", rating: 8.4, genres: ["K-Drama", "Romance", "Comedy"], overview: "In disguise as her friend, Ha-ri shows up to a blind date to scare him away. But plans go awry when he turns out to be her CEO.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/394/986401.jpg" },
  { id: "tv-stranger-things", title: "Stranger Things", mediaType: "tv", year: "2016 • 4 Seasons", rating: 8.6, genres: ["Sci-Fi", "Mystery", "Drama"], overview: "When a young boy vanishes, a small town uncovers a mystery involving secret experiments, terrifying supernatural forces and one strange little girl.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/595/1489169.jpg" },
  { id: "tv-arcane", title: "Arcane", mediaType: "tv", year: "2021 • 2 Seasons", rating: 9.0, genres: ["Anime", "Animation", "Sci-Fi", "Action"], overview: "Set in the utopian region of Piltover and the oppressed underground of Zaun, the story follows the origins of two iconic League champions.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/536/1340287.jpg" },
  { id: "tv-spy-family", title: "Spy x Family", mediaType: "tv", year: "2022 • 2 Seasons", rating: 8.6, genres: ["Anime", "Comedy", "Action"], overview: "A spy on an undercover mission marries a telepathic girl and a professional assassin, with none of them knowing each other's secrets.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/590/1477119.jpg" },
  { id: "tv-frieren", title: "Frieren: Beyond Journey's End", mediaType: "tv", year: "2023 • 1 Season", rating: 9.1, genres: ["Anime", "Fantasy", "Adventure"], overview: "An elven mage reflecting on the fleeting lives of her former human companions embarks on a new adventure across the realm.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/479/1198409.jpg" },
  { id: "tv-last-of-us", title: "The Last of Us", mediaType: "tv", year: "2023 • 1 Season", rating: 8.6, genres: ["Drama", "Sci-Fi", "Action"], overview: "Twenty years after a fungal outbreak ravages the planet, survivors Joel and Ellie must journey across what remains of America.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/563/1409008.jpg" },
  { id: "tv-modern-family", title: "Modern Family", mediaType: "tv", year: "2009 • 11 Seasons", rating: 8.5, genres: ["Comedy", "Family"], overview: "Three different but related families face trials and tribulations in their own uniquely comedic ways.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/359/898320.jpg" },
  { id: "tv-avatar-airbender", title: "Avatar: The Last Airbender", mediaType: "tv", year: "2005 • 3 Seasons", rating: 8.8, genres: ["Anime", "Animation", "Fantasy", "Action"], overview: "In a war-torn world of elemental magic, a young boy reawakens to undertake a dangerous mystic quest to fulfill his destiny.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/633/1582667.jpg" },
  { id: "tv-demon-slayer", title: "Demon Slayer: Kimetsu no Yaiba", mediaType: "tv", year: "2019 • 4 Seasons", rating: 8.7, genres: ["Anime", "Action", "Fantasy"], overview: "A family is attacked by demons and only two members survive - Tanjiro and his sister Nezuko, who is turning into a demon herself.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/456/1140750.jpg" },
  { id: "tv-jujutsu-kaisen", title: "Jujutsu Kaisen", mediaType: "tv", year: "2020 • 2 Seasons", rating: 8.6, genres: ["Anime", "Action", "Fantasy"], overview: "A boy swallows a cursed talisman - the finger of a demon - and becomes cursed himself.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/608/1521905.jpg" },
  { id: "tv-attack-on-titan", title: "Attack on Titan", mediaType: "tv", year: "2013 • 4 Seasons", rating: 9.1, genres: ["Anime", "Action", "Fantasy"], overview: "After his hometown is destroyed and his mother is killed, young Eren Jaeger vows to cleanse the earth of the giant humanoid Titans.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/632/1582290.jpg" },
  { id: "tv-wednesday", title: "Wednesday", mediaType: "tv", year: "2022 • 1 Season", rating: 8.1, genres: ["Comedy", "Fantasy", "Mystery"], overview: "Follows Wednesday Addams' years as a student, attempting to master her emerging psychic ability and solve a mystery.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/586/1466410.jpg" },
  { id: "tv-bridgerton", title: "Bridgerton", mediaType: "tv", year: "2020 • 3 Seasons", rating: 7.4, genres: ["Romance", "Drama"], overview: "Wealth, lust, and betrayal set against the backdrop of Regency-era England, seen through the eyes of the powerful Bridgerton family.", poster: "https://static.tvmaze.com/uploads/images/original_untouched/614/1535959.jpg" },

  // --- MOVIES ---
  { id: "movie-your-name", title: "Your Name.", mediaType: "movie", year: "2016", rating: 8.5, genres: ["Anime", "Romance", "Drama"], overview: "Two teenagers share a profound, magical connection upon discovering they are swapping bodies.", poster: "https://m.media-amazon.com/images/M/MV5BMjI1ODZkYTgtYTY3Yy00ZTJkLWFkOTgtZDUyYWM4MzQwNjk0XkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-interstellar", title: "Interstellar", mediaType: "movie", year: "2014", rating: 8.7, genres: ["Sci-Fi", "Drama", "Adventure"], overview: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.", poster: "https://m.media-amazon.com/images/M/MV5BYzdjMDAxZGItMjI2My00ODA1LTlkNzItOWFjMDU5ZDJlYWY3XkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-spirited-away", title: "Spirited Away", mediaType: "movie", year: "2001", rating: 8.5, genres: ["Anime", "Fantasy", "Adventure"], overview: "During her family's move to the suburbs, a sullen 10-year-old girl wanders into a world ruled by gods, witches and spirits.", poster: "https://m.media-amazon.com/images/M/MV5BNTEyNmEwOWUtYzkyOC00ZTQ4LTllZmUtMjk0Y2YwOGUzYjRiXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-eternal-sunshine", title: "Eternal Sunshine of the Spotless Mind", mediaType: "movie", year: "2004", rating: 8.1, genres: ["Romance", "Sci-Fi", "Drama"], overview: "When their relationship turns sour, a couple undergoes a medical procedure to have each other erased from their memories.", poster: "https://m.media-amazon.com/images/M/MV5BMTY4NzcwODg3Nl5BMl5BanBnXkFtZTcwNTEwOTMyMw@@._V1_SX1000.jpg" },
  { id: "movie-dnd", title: "Dungeons & Dragons: Honor Among Thieves", mediaType: "movie", year: "2023", rating: 7.4, genres: ["Action", "Comedy", "Adventure"], overview: "A charming thief and a band of unlikely adventurers undertake an epic heist to retrieve a lost relic.", poster: "https://m.media-amazon.com/images/M/MV5BOGRjMjQ0ZDAtODc0OS00MGY1LTkxMTMtODhhNjY5NTM4N2IwXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-parasite", title: "Parasite", mediaType: "movie", year: "2019", rating: 8.5, genres: ["Comedy", "Thriller", "Drama"], overview: "Greed and class discrimination threaten the newly formed symbiotic relationship between the wealthy Park family and the destitute Kim clan.", poster: "https://m.media-amazon.com/images/M/MV5BYjk1Y2U4MjQtY2ZiNS00OWQyLWI3MmYtZWUwNmRjYWRiNWNhXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-spider-verse", title: "Spider-Man: Across the Spider-Verse", mediaType: "movie", year: "2023", rating: 8.4, genres: ["Animation", "Action", "Sci-Fi"], overview: "Miles Morales catapults across the Multiverse, where he encounters a team of Spider-People charged with protecting its existence.", poster: "https://m.media-amazon.com/images/M/MV5BNThiZjA3MjItZGY5Ni00ZmJhLWEwN2EtOTBlYTA4Y2E0M2ZmXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-avatar", title: "Avatar", mediaType: "movie", year: "2009", rating: 7.6, genres: ["Action", "Sci-Fi", "Adventure"], overview: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between orders and protecting an alien world.", poster: "https://m.media-amazon.com/images/M/MV5BMDEzMmQwZjctZWU2My00MWNlLWE0NjItMDJlYTRlNGJiZjcyXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-soul", title: "Soul", mediaType: "movie", year: "2020", rating: 8.1, genres: ["Animation", "Comedy", "Fantasy"], overview: "After landing the gig of a lifetime, a New York jazz pianist suddenly finds himself trapped in a strange land between Earth and the afterlife.", poster: "https://m.media-amazon.com/images/M/MV5BZTZkYjA5MDEtMjY1ZC00ODk5LThjOTUtZDYxODEzYWNjMTU2XkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-dune-2", title: "Dune: Part Two", mediaType: "movie", year: "2024", rating: 8.2, genres: ["Sci-Fi", "Adventure", "Action"], overview: "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family.", poster: "https://m.media-amazon.com/images/M/MV5BNTc0YmQxMjEtODI5MC00NjFiLTlkMWUtOGQ5NjFmYWUyZGJhXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-lion-king", title: "The Lion King", mediaType: "movie", year: "1994", rating: 8.3, genres: ["Animation", "Drama", "Family"], overview: "Lion prince Simba and his father are targeted by his bitter uncle, who wants to ascend the throne himself.", poster: "https://m.media-amazon.com/images/M/MV5BZGRiZDZhZjItM2M3ZC00Y2IyLTk3Y2MtMWY5YjliNDFkZTJlXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-titanic", title: "Titanic", mediaType: "movie", year: "1997", rating: 7.9, genres: ["Drama", "Romance"], overview: "A seventeen-year-old aristocrat falls in love with a kind but poor artist aboard the luxurious, ill-fated R.M.S. Titanic.", poster: "https://m.media-amazon.com/images/M/MV5BYzYyN2FiZmUtYWYzMy00MzViLWJkZTMtOGY1ZjgzNWMwN2YxXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-lala-land", title: "La La Land", mediaType: "movie", year: "2016", rating: 8.0, genres: ["Comedy", "Drama", "Romance"], overview: "While navigating their careers in Los Angeles, a pianist and an actress fall in love while attempting to reconcile their aspirations.", poster: "https://m.media-amazon.com/images/M/MV5BMzUzNDM2NzM2MV5BMl5BanBnXkFtZTgwNTM3NTg4OTE@._V1_SX1000.jpg" },
  { id: "movie-everything-everywhere", title: "Everything Everywhere All at Once", mediaType: "movie", year: "2022", rating: 7.8, genres: ["Action", "Adventure", "Comedy", "Sci-Fi"], overview: "A middle-aged Chinese immigrant is swept up into an insane adventure in which she alone can save existence by exploring other universes.", poster: "https://m.media-amazon.com/images/M/MV5BOWNmMzAzZmQtNDQ1NC00Nzk5LTkyMmUtNGI2N2NkOWM4MzEyXkEyXkFqcGc@._V1_SX1000.jpg" },
  { id: "movie-oppenheimer", title: "Oppenheimer", mediaType: "movie", year: "2023", rating: 8.8, genres: ["Biography", "Drama", "History"], overview: "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb.", poster: "https://m.media-amazon.com/images/M/MV5BN2JkMDc5MGQtZjg3YS00NmFiLWIyZmQtZTJmNTM5MjVmYTQ4XkEyXkFqcGc@._V1_SX1000.jpg" }
];

function check(url) {
  return new Promise((resolve) => {
    https.get(url, (res) => {
      resolve(res.statusCode);
    }).on('error', () => resolve(0));
  });
}

async function run() {
  console.log(`Checking ${catalog.length} titles...`);
  let ok = 0;
  for (const item of catalog) {
    const code = await check(item.poster);
    if (code === 200) {
      ok++;
      console.log(`✓ [200] ${item.title}`);
    } else {
      console.log(`✗ [${code}] ${item.title}: ${item.poster}`);
    }
  }
  console.log(`\nResult: ${ok}/${catalog.length} verified 200 OK!`);
}

run();
