pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
    }
}

rootProject.name = "Komorebi"
include ':app'

def capSettings = file("capacitor.settings.gradle")
if (capSettings.exists()) {
    apply from: 'capacitor.settings.gradle'
}
